AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3

Resources:
  VideoProcessingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: videoprocessingbucket

  VideoCompressorLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: video_compressor/
      Handler: app.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
      - x86_64
      Events:
        S3ObjectCreatedMP4:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mp4
        S3ObjectCreatedMOV:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mov
        S3ObjectCreatedWMV:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .wmv
        S3ObjectCreatedFLV:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .flv
        S3ObjectCreatedAVI:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .avi
        S3ObjectCreatedMKV:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mkv
        S3ObjectCreatedWEBM:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .webm
        S3ObjectCreatedMPEG:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mpeg
        S3ObjectCreatedVOB:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .vob
        S3ObjectCreatedM4V:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .m4v
        S3ObjectCreatedH264:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .h264
        S3ObjectCreatedTS:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .ts
        S3ObjectCreatedMTS:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mts
        S3ObjectCreatedDIVX:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .divx
        S3ObjectCreatedXVID:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .xvid
        S3ObjectCreatedF4V:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .f4v
        S3ObjectCreatedMXF:
          Type: S3
          Properties:
            Bucket: !Ref VideoProcessingBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mxf
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: arn:aws:s3:::videoprocessingbucket/*
        - PolicyName: LambdaCloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*